# -*- coding: utf-8 -*-
"""Transvolt a2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KlZqc7CbduR3TX8EGWGqbDdi2YTeSL4
"""

import pandas as pd
# Loading the CSV
df = pd.read_csv("/content/Sample_Data.csv")
df.head()

# Convert Timestamp to datetime
df['Timestamp'] = pd.to_datetime(df['Timestamp'], dayfirst=True)
# Drop any missing values
df.dropna(inplace=True)
df.info()

Q1 = df['Values'].quantile(0.25)
Q3 = df['Values'].quantile(0.75)
IQR = Q3 - Q1
# Keep only data within acceptable range
df_clean = df[(df['Values'] >= Q1 - 1.5 * IQR) & (df['Values'] <= Q3 + 1.5 * IQR)]

min_val = df_clean['Values'].min()
max_val = df_clean['Values'].max()
avg_val = df_clean['Values'].mean()
print("Min:", min_val)
print("Max:", max_val)
print("Average:", avg_val)

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.hist(df_clean['Values'], bins=30, color='skyblue', edgecolor='black')
plt.title('Histogram of Values')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Filter for rows where day is 12
df_12 = df_clean[df_clean['Timestamp'].dt.day == 12]

# Create color list
colors = ['red' if val < avg_val else 'blue' for val in df_12['Values']]

# Plot
plt.figure(figsize=(12, 6))
plt.bar(df_12['Timestamp'].dt.strftime('%Y-%m-%d %H:%M'), df_12['Values'], color=colors)
plt.axhline(avg_val, color='gray', linestyle='--', label=f'Average: {avg_val:.2f}')
plt.title('Values on the 12th of Each Month')
plt.xlabel('Timestamp')
plt.ylabel('Values')
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

print("No data available for the 12th of any month.")